

CREATE TABLE users (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  username VARCHAR(60) NOT NULL UNIQUE,
  email VARCHAR(190) NOT NULL UNIQUE,
  phone VARCHAR(30) NULL,
  photo_key VARCHAR(255) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(40) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE security_guard_permissions (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  description TEXT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  granted_by INT  NOT NULL,
  granted_to INT  NULL,
  permission_start TIMESTAMP NULL,
  permission_end TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (granted_to) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE security_visit_requests (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_type VARCHAR(40) NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  purpose VARCHAR(60) NOT NULL DEFAULT 'visit',
  arrival_time TIMESTAMP NOT NULL,
  description TEXT NULL,
  student_name VARCHAR(120) NULL,
  photo_data TEXT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  review_comment TEXT NULL,
  reviewed_by INT  NULL,
  reviewed_at TIMESTAMP NULL,
  created_by INT  NULL,
  language VARCHAR(40) NOT NULL DEFAULT 'en',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE otp_challenges (
  id CHAR(36) PRIMARY KEY,
  user_id INT  NOT NULL,
  code_hash CHAR(64) NOT NULL,
  channel VARCHAR(40) NOT NULL,
  destination_mask VARCHAR(190) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  attempts SMALLINT  NOT NULL DEFAULT 0,
  consumed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE classes (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE,
  academic_year VARCHAR(20) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE subjects (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(30) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE students (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT  NULL UNIQUE,
  admission_number VARCHAR(40) NOT NULL UNIQUE,
  full_name VARCHAR(120) NOT NULL,
  photo_key VARCHAR(255) NULL,
  gender VARCHAR(40) NOT NULL,
  birthday DATE NOT NULL,
  academic_year VARCHAR(20) NOT NULL,
  class_name VARCHAR(80) NOT NULL,
  date_of_birth DATE NULL,
  parent_phone VARCHAR(30) NULL,
  qr_token CHAR(36) NOT NULL UNIQUE,
  conduct_score SMALLINT  NOT NULL DEFAULT 100,
  conduct_updated_at TIMESTAMP NULL DEFAULT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE student_classes (
  student_id INT  NOT NULL,
  class_id INT  NOT NULL,
  enrolled_at DATE NOT NULL,
  PRIMARY KEY (student_id, class_id),
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE TABLE teacher_assignments (
  teacher_id INT  NOT NULL,
  class_id INT  NOT NULL,
  subject_id INT  NOT NULL,
  PRIMARY KEY (teacher_id, class_id, subject_id),
  FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
  FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

CREATE TABLE parent_students (
  parent_id INT  NOT NULL,
  student_id INT  NOT NULL,
  relationship VARCHAR(40) NOT NULL,
  PRIMARY KEY (parent_id, student_id),
  FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE applications (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_name VARCHAR(120) NOT NULL,
  applicant_photo_key VARCHAR(255) NULL,
  mother_name VARCHAR(120) NULL,
  mother_phone VARCHAR(30) NULL,
  father_name VARCHAR(120) NULL,
  father_phone VARCHAR(30) NULL,
  parent_phone VARCHAR(30) NOT NULL,
  parent_email VARCHAR(190) NOT NULL,
  province VARCHAR(80) NULL,
  district VARCHAR(80) NULL,
  sector VARCHAR(80) NULL,
  cell VARCHAR(80) NULL,
  village VARCHAR(80) NULL,
  desired_class VARCHAR(80) NOT NULL,
  gender VARCHAR(40) NULL,
  birthday DATE NULL,
  previous_school VARCHAR(160) NULL,
  result_slip_key VARCHAR(255) NULL,
  report_key VARCHAR(255) NULL,
  academic_year VARCHAR(20) NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  approved_at TIMESTAMP NULL,
  reviewer_comment TEXT NULL,
  approved_student_id INT  NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE attendance (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INT  NOT NULL,
  attendance_date DATE NOT NULL,
  status VARCHAR(40) NOT NULL,
  comment TEXT NULL,
  marked_by INT  NOT NULL,
  score_deduction SMALLINT  NOT NULL DEFAULT 0,
  UNIQUE (student_id, attendance_date),
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (marked_by) REFERENCES users(id)
);

CREATE TABLE fees (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INT  NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  reference VARCHAR(80) NOT NULL UNIQUE,
  paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE notices (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  body TEXT NOT NULL,
  audience VARCHAR(40) NOT NULL DEFAULT 'all',
  published_by INT  NOT NULL,
  published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (published_by) REFERENCES users(id)
);

CREATE TABLE tests (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  class_id INT  NOT NULL,
  subject_id INT  NOT NULL,
  teacher_id INT  NOT NULL,
  duration_minutes SMALLINT  NOT NULL,
  starts_at TIMESTAMP NULL,
  ends_at TIMESTAMP NULL,
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (class_id) REFERENCES classes(id),
  FOREIGN KEY (subject_id) REFERENCES subjects(id),
  FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE TABLE test_questions (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id INT  NOT NULL,
  question_order SMALLINT  NOT NULL,
  question_type VARCHAR(40) NOT NULL,
  prompt TEXT NOT NULL,
  options_json JSON NULL,
  answer_json JSON NOT NULL,
  points DECIMAL(6,2) NOT NULL DEFAULT 1,
  UNIQUE (test_id, question_order),
  FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE
);

CREATE TABLE test_attempts (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id INT  NOT NULL,
  student_id INT  NOT NULL,
  started_at TIMESTAMP NOT NULL,
  submitted_at TIMESTAMP NULL,
  score DECIMAL(7,2) NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'in_progress',
  UNIQUE (test_id, student_id),
  FOREIGN KEY (test_id) REFERENCES tests(id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE grades (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INT  NOT NULL,
  subject_id INT  NOT NULL,
  assessment_name VARCHAR(120) NOT NULL,
  score DECIMAL(7,2) NOT NULL,
  max_score DECIMAL(7,2) NOT NULL,
  recorded_by INT  NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (subject_id) REFERENCES subjects(id),
  FOREIGN KEY (recorded_by) REFERENCES users(id)
);

CREATE TABLE timetable_entries (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id INT  NOT NULL,
  subject_id INT  NOT NULL,
  teacher_id INT  NOT NULL,
  day_of_week SMALLINT  NOT NULL,
  starts_at TIME NOT NULL,
  ends_at TIME NOT NULL,
  room VARCHAR(80) NULL,
  FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
  FOREIGN KEY (subject_id) REFERENCES subjects(id),
  FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE TABLE teacher_profiles (
  user_id INT  PRIMARY KEY,
  employee_number VARCHAR(40) NOT NULL UNIQUE,
  qr_token CHAR(36) NOT NULL UNIQUE,
  national_id VARCHAR(40) NULL UNIQUE,
  contract_type VARCHAR(40) NOT NULL DEFAULT 'permanent',
  contract_start DATE NULL,
  contract_end DATE NULL,
  salary DECIMAL(12,2) NULL,
  gender VARCHAR(40) NULL,
  birthday DATE NULL,
  diploma_key VARCHAR(255) NULL,
  subject_or_module VARCHAR(160) NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE staff_attendance (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT  NOT NULL,
  attendance_date DATE NOT NULL,
  status VARCHAR(40) NOT NULL,
  marked_by INT  NOT NULL,
  UNIQUE (user_id, attendance_date),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (marked_by) REFERENCES users(id)
);

CREATE TABLE leave_requests (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT  NOT NULL,
  leave_type VARCHAR(40) NOT NULL,
  starts_on DATE NOT NULL,
  ends_on DATE NOT NULL,
  reason TEXT NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  reviewed_by INT  NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

CREATE TABLE payroll_records (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT  NOT NULL,
  period_month DATE NOT NULL,
  gross_amount DECIMAL(12,2) NOT NULL,
  deductions DECIMAL(12,2) NOT NULL DEFAULT 0,
  net_amount DECIMAL(12,2) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'draft',
  approved_by INT  NULL,
  UNIQUE (user_id, period_month),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE TABLE invoices (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INT  NOT NULL,
  invoice_number VARCHAR(60) NOT NULL UNIQUE,
  description VARCHAR(180) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  due_date DATE NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'unpaid',
  created_by INT  NOT NULL,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE expenses (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(100) NOT NULL,
  description VARCHAR(180) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  spent_at DATE NOT NULL,
  photo_url VARCHAR(500) NULL,
  document_url VARCHAR(500) NULL,
  video_url VARCHAR(500) NULL,
  budget_status VARCHAR(40) NOT NULL DEFAULT 'less',
  recorded_by INT  NOT NULL,
  FOREIGN KEY (recorded_by) REFERENCES users(id)
);

CREATE TABLE budgets (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  fiscal_year VARCHAR(20) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  description TEXT NULL,
  photo_url VARCHAR(500) NULL,
  document_url VARCHAR(500) NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'draft',
  created_by INT  NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE transport_routes (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  bus_number VARCHAR(40) NOT NULL UNIQUE,
  driver_name VARCHAR(120) NOT NULL,
  driver_phone VARCHAR(30) NOT NULL,
  capacity SMALLINT  NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE student_transport (
  student_id INT  PRIMARY KEY,
  route_id INT  NOT NULL,
  pickup_point VARCHAR(160) NOT NULL,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (route_id) REFERENCES transport_routes(id) ON DELETE CASCADE
);

CREATE TABLE inventory_items (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(140) NOT NULL,
  category VARCHAR(80) NOT NULL,
  quantity INT NOT NULL DEFAULT 0,
  reorder_level INT NOT NULL DEFAULT 0,
  unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0,
  location VARCHAR(100) NULL,
  updated_by INT  NOT NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE inventory_transactions (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id INT  NOT NULL,
  type VARCHAR(40) NOT NULL,
  quantity INT  NOT NULL,
  note VARCHAR(255) NULL,
  moved_by INT  NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
  FOREIGN KEY (moved_by) REFERENCES users(id)
);

CREATE TABLE assets (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(140) NOT NULL,
  asset_tag VARCHAR(60) NOT NULL UNIQUE,
  category VARCHAR(80) NOT NULL,
  condition_status VARCHAR(40) NOT NULL DEFAULT 'good',
  location VARCHAR(100) NULL,
  assigned_to INT  NULL,
  acquired_on DATE NULL,
  FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE library_books (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  isbn VARCHAR(30) NULL UNIQUE,
  title VARCHAR(180) NOT NULL,
  author VARCHAR(140) NOT NULL,
  subject VARCHAR(100) NULL,
  quantity INT  NOT NULL DEFAULT 1,
  available_quantity INT  NOT NULL DEFAULT 1,
  shelf VARCHAR(50) NULL,
  created_by INT  NOT NULL,
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE library_loans (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id INT  NOT NULL,
  student_id INT  NOT NULL,
  issued_at DATE NOT NULL,
  due_at DATE NOT NULL,
  returned_at DATE NULL,
  issued_by INT  NOT NULL,
  FOREIGN KEY (book_id) REFERENCES library_books(id),
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (issued_by) REFERENCES users(id)
);

CREATE TABLE feeding_records (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INT  NOT NULL,
  feeding_date DATE NOT NULL,
  served BOOLEAN NOT NULL DEFAULT TRUE,
  meal_type VARCHAR(60) NOT NULL,
  recorded_by INT  NOT NULL,
  UNIQUE (student_id, feeding_date, meal_type),
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (recorded_by) REFERENCES users(id)
);

CREATE TABLE feeding_stock (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_name VARCHAR(120) NOT NULL,
  quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
  unit VARCHAR(30) NOT NULL,
  reorder_level DECIMAL(12,2) NOT NULL DEFAULT 0,
  updated_by INT  NOT NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE documents (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  document_type VARCHAR(40) NOT NULL,
  storage_key VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  file_size BIGINT  NOT NULL,
  visibility VARCHAR(40) NOT NULL DEFAULT 'admin',
  uploaded_by INT  NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE TABLE notifications (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id INT  NOT NULL,
  channel VARCHAR(40) NOT NULL DEFAULT 'in_app',
  title VARCHAR(180) NOT NULL,
  message TEXT NOT NULL,
  sent_at TIMESTAMP NULL,
  read_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE homework (
  id INT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  description TEXT NOT NULL,
  class_id INT  NOT NULL,
  subject_id INT  NOT NULL,
  teacher_id INT  NOT NULL,
  due_date DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (class_id) REFERENCES classes(id),
  FOREIGN KEY (subject_id) REFERENCES subjects(id),
  FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE TABLE behavior_records (
  id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INT  NOT NULL,
  category VARCHAR(40) NOT NULL,
  note TEXT NOT NULL,
  recorded_by INT  NOT NULL,
  score_deduction SMALLINT  NOT NULL DEFAULT 0,
  score_after SMALLINT  NULL,
  attendance_id BIGINT  NULL,
  UNIQUE (attendance_id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (recorded_by) REFERENCES users(id)
);
